/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLoginRouteImport } from './routes/user-login'
import { Route as IndexRouteImport } from './routes/index'

const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user-login',
  path: '/user-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-login': typeof UserLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-login': typeof UserLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user-login': typeof UserLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user-login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user-login'
  id: '__root__' | '/' | '/user-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserLoginRoute: typeof UserLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-login': {
      id: '/user-login'
      path: '/user-login'
      fullPath: '/user-login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserLoginRoute: UserLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
